### ISSUE TITLE
Add pycharm-eap alias to PyCharm

### ISSUE THREAD

**Issue by Ashark** [alex1701c/jetbrains-api#6]
Hello.
To be able to use a pycharm-eap package with the jetbrains runner, I had to add the following to the `SettingsDirectory::getAliases()`:
```cpp
 {"PyCharm Professional (EAP)",    "PyCharm"},
```

![image](https://github.com/alex1701c/jetbrains-api/assets/22634975/0ada1806-744f-4b71-afcb-0eb76505a4a2)

Can you please add this alias there?

**Comment by alex1701c** [comment]
Sorry, I forgot about this issue. Can you make a PR? :)

**Comment by Ashark** [comment]
While the manual mapping works, still it is better to make it automatically when possible.
